[gcp_service_account]
type = "service_account"
project_id = "make-442407"
private_key_id = "2a3e0e485c4e7846318b2bfefd1f6d13eb7d446d"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXaUhlqXNYXwHE
BxzV+CxP6Z7n97owb62M5QGEmes/IoGKFDM93pLF2TzHaa/8GIrUdL7KrVx7zQ4h
irYMcXEiN+pZDVf4+CswNurLadQtk7dB/29UqueDJYxP8N+L6Ukhpe/VCrwcW1Fy
iD6SNv+GU4+Z0kPKG8mxeZAK9hsta8cvW2YaxYvSx1dO/E4+AZhy3vse7X2oSDe5
9rhl2QdXgvq3JoKoTykzCz7s7DEU3MSew4gk3yBPyfEU2sUumBuH3Nr9HuTjSV+f
qvAY3dAGxFDCe4dy4OPCLVLOCK/x3SewOw3Vvx7syLQORTgUn6dcnj5CLa/9YTa2
Suc82YP3AgMBAAECggEAVQKEIzaxwgzQbhOegiSsHCdm4kWl8WqJU6KmrDVwHNzZ
wWvCYya8xp66OTpQzMzEsR6XkvXCm0rryjnrKVL1olrtvZIiByutI5xwobEUnp3+
…(중간에 가공 없이 “한 글자도 빠짐없이”)…
-----END PRIVATE KEY-----
"""
client_email = "lotto-app-sa@make-442407.iam.gserviceaccount.com"
client_id = "112609156907569631402"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/lotto-app-sa%40make-442407.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
